// <auto-generated />
using System;
using AustoPredictor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AustoPredictor.Data.Migrations
{
    [DbContext(typeof(AustoPredictorDbContext))]
    [Migration("20260921223332_AddPredictionDesignation")]
    partial class AddPredictionDesignation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AustoPredictor.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AustoPredictor.Data.Entities.PlayerPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Designation")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PredictedPosition")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("PlayerId", "PredictedPosition")
                        .IsUnique();

                    b.HasIndex("PlayerId", "TeamId")
                        .IsUnique();

                    b.ToTable("PlayerPredictions");
                });

            modelBuilder.Entity("AustoPredictor.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bath"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bristol Bears"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Exeter Chiefs"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gloucester"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Harlequins"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Leicester Tigers"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Newcastle Red Bulls"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Northampton Saints"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sale Sharks"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Saracens"
                        });
                });

            modelBuilder.Entity("AustoPredictor.Data.Entities.PlayerPrediction", b =>
                {
                    b.HasOne("AustoPredictor.Data.Entities.Player", "Player")
                        .WithMany("Predictions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AustoPredictor.Data.Entities.Team", "Team")
                        .WithMany("Predictions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AustoPredictor.Data.Entities.Player", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("AustoPredictor.Data.Entities.Team", b =>
                {
                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
